### ISSUE TITLE
Collaborate on everything!

### ISSUE THREAD

**Issue by probablylerebear** [lerebear/friendly-robot#11]
Please give me a 👍 when you receive a push notification for this issue.

@Iron-Ham, @shayfrendt

**Comment by probablylerebear** [comment]
Bringing in @nplasterer, @rnystrom and @brianlovin. Again, 👍 when you get this please!

**Comment by Iron-Ham** [comment]
One more try @rnysteom @brianlovin @shayfrendt @colinkeany @becca

**Comment by lerebear** [comment]
@Iron-Ham, please acknowledge this via Slack if you receive a push for it!
